name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and publish the image
        run: |
          docker login -u gwashel -p ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/gwashel/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/gwashel/arithmetic-service:latest
